### ISSUE TITLE
incorrect shape in nc_vest_20.shp

### ISSUE THREAD

**Issue by rootsmusic** [nonpartisan-redistricting-datahub/erj-nc#2]
@spencer-rdh  Please note issue opened at [https://github.com/nonpartisan-redistricting-datahub/pdv-nc/issues/5](https://github.com/nonpartisan-redistricting-datahub/pdv-nc/issues/5), because the minor boundary difference would affect Buncombe and its neighboring county if using maup.

**Comment by spencer-rdh** [comment]
Hello. Thanks for pointing out this discrpency from what VEST has and what the county has. However, VEST has confirmed that the Buncombe County precinct shapes are from what the county had on their website as of November 2020, which is when the election was. VEST may check with the Buncombe County BOE to see when exactly that county was changed. 

This discrepency is actually rectified by maup anyway (rather than causing an issue) because the area that is included in the VEST shape and not in the county shape is only part of one block, and that block has the majority of it's area in the neighboring precinct, so all disaggregated data is assigned to that precinct (Buncombe 68.1 at West Buncombe School) not to Buncombe 681 (Newfound Community Center). This also should not affect any other county as the area of difference is entirely within Buncombe County.

Supporting documentation attached. See page 9 of 09-24-19.pdf for image of 681 precinct boundaries, cc_congressionaldistrict for countywide image of precincts, and the screenshot to see the block (in red) which has less than 50% of it's area in precinct 681.
[09-24-19.pdf](https://github.com/nonpartisan-redistricting-datahub/erj-nc/files/10248280/09-24-19.pdf)
![cc_congressionaldistrict](https://user-images.githubusercontent.com/72453434/208168070-a144468a-790d-42e9-bbaf-a67ac7f713e4.jpg)
![Screenshot 2022-12-16 102650](https://user-images.githubusercontent.com/72453434/208168217-abdaa070-2c8c-424c-a68a-38751e38576b.jpg)

**Comment by rootsmusic** [comment]
Thanks @spencer-rdh, Buncombe's BOE should have the accurate shape.  (I received that allegedly correct shape from the State's BOE.)
